# Generated by Django 5.0.6 on 2024-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextToSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("audio_file", models.FileField(upload_to="audio/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
